<a href="https://colab.research.google.com/github/AanchalA/Reinforcement-Learning/blob/main/OpenAI_Gym_and_Python_for_Q_learning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- https://www.youtube.com/watch?v=QK_PP_2KgGE&list=PLZbbT5o_s2xoWNVdDudn51XM8lOuZ_Njv&index=8&ab_channel=deeplizard

- https://deeplizard.com/learn/video/QK_PP_2KgGE

In [ ]:
! pip install gym >> /dev/null

In [ ]:
import gym
import time
import random
import numpy as np
from IPython.display import clear_output

In [ ]:
# Creating The Environment
env = gym.make('FrozenLake-v1', render_mode='ansi', new_step_api=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
# Creating The Q-Table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Initializing Q-Learning Parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = list()

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        # Taking Action
        new_state, reward, done, truncated, info = env.step(action)

        # Update The Q-Value
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition To The Next State
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    # Exploration Rate Decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

In [ ]:
# After All Episodes Complete Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.03000000000000002
2000 :  0.23000000000000018
3000 :  0.4130000000000003
4000 :  0.5630000000000004
5000 :  0.6330000000000005
6000 :  0.6770000000000005
7000 :  0.6950000000000005
8000 :  0.6480000000000005
9000 :  0.6780000000000005
10000 :  0.6850000000000005


In [ ]:
# Interpreting The Training Results - Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.54606984 0.49480354 0.48875256 0.50061903]
 [0.30718494 0.32251736 0.24413677 0.48995063]
 [0.42629731 0.39050749 0.41578776 0.45999204]
 [0.24192344 0.31013562 0.22454492 0.42868262]
 [0.564812   0.45661542 0.40341337 0.35005812]
 [0.         0.         0.         0.        ]
 [0.17466563 0.21747065 0.26263505 0.1586251 ]
 [0.         0.         0.         0.        ]
 [0.2607091  0.40455796 0.37577634 0.59921293]
 [0.4092045  0.67794198 0.44569473 0.35004906]
 [0.64103694 0.33665908 0.37982628 0.37895398]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.50962242 0.41521012 0.79562639 0.42266933]
 [0.71979896 0.92521661 0.76188135 0.71285839]
 [0.         0.         0.         0.        ]]


In [ ]:
# The Code To Watch The Agent Play The Game
# Watch our agent play Frozen Lake by playing the best action
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("***** EPISODE ", episode + 1, " *****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state
        # Take new action
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, truncated, info = env.step(action)

        if done:
            clear_output(wait=True)
            print(env.render())

            if reward == 1:
                print("**** You reached the goal! ****")
                time.sleep(3)

            else:
                print("**** You fell through a hole! ****")
                time.sleep(3)
                clear_output(wait=True)

            break

        # Set new state
        state = new_state

env.close()

['  (Right)\nSFFF\nFHF\x1bH\x1b\nFFFH\nHFFG\n']
**** You fell through a hole! ****


In [ ]:
env.render?